spring:
  datasource:
    jdbcUrl: jdbc:mysql://133.186.201.56:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: BeSt3489!!
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jdbc:
  datasource:
    jdbcUrl: jdbc:mysql://114.110.160.89:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: firewall
    password: best3489##
    driverClassName: com.mysql.cj.jdbc.Driver
